name: contrastive
dataset: FACAD
cltidx2desc_global: "labels.csv"
attr2desc_local: "attr2desc_new_en.txt"
labelfile_name: "cropimgpth2labels_multi_33_drop07.csv"
local_img_dir: "images_crop2"
global_img_dir: "images"
lr: 1e-5
milestones: [30, 40]
batch_size: 100
num_epochs: 10
num_folds: 5
val_fold: 0
seed: 42
train_mode: test # test