dataset_config:
  fashioniq:
      data_dir: ${env.data_dir}/datasets
      use_images: true
      use_features: false
      garment_class: all
      images:
        train:
        - FashionIQ/images
        val:
        - FashionIQ/images
        test:
        - FashionIQ/images
      annotations:
        train:
        - FashionIQ/captions
        val:
        - FashionIQ/captions
        test:
        - FashionIQ/captions
      features:
        train:
        - FashionIQ/features
        val:
        - FashionIQ/features
        test:
        - FashionIQ/features
      processors:
        text_processor:
          type: bert_tokenizer
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0
            max_seq_length: 50
        train_image_processor:
          type: torchvision_transforms
          params:
            transforms:
              - type: RandomResizedCrop
                params:
                  size: [224, 224]
                  scale: [0.8, 1.0]
                  ratio: [0.75, 1.3]
              - RandomHorizontalFlip
              - ToTensor
              - type: Normalize
                params:
                  mean: [0.46777044, 0.44531429, 0.40661017]
                  std: [0.12221994, 0.12145835, 0.14380469]
        eval_image_processor:
          type: torchvision_transforms
          params:
            transforms:
              - type: Resize
                params:
                  size: [224, 224]
              - ToTensor
              - type: Normalize
                params:
                  mean: [0.46777044, 0.44531429, 0.40661017]
                  std: [0.12221994, 0.12145835, 0.14380469]
