model_config:
  csa_net:
    image_channel: 512
    n_categories: 153
    n_conditions: 5
    feature_dim: 64

    image_encoder:
      type: torchvision_resnet
      params:
        name: resnet18
        pretrained: true
        zero_init_residual: false
        num_output_features: 1
        pool_type: avg

    losses:
    - type: triplet_loss
      params:
        margin: 0.3
